version: '3.8'

services:
  flask-server:
    build: .
    ports:
      - "5001:5000"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
  bob:
    build: ../client
    tty: true

  alice:
    build: ../client
    tty: true 

volumes:
  mongo-data:
