version: '3.8'

services:
  flask-server:
    build: .
    ports:
      - "5001:5000"
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
  bob-db:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - bob-mongo-data:/data/db

  alice-db:
    image: mongo:latest
    ports:
      - "27019:27017"
    volumes:
      - alice-mongo-data:/data/db

volumes:
  mongo-data:
  bob-mongo-data:
  alice-mongo-data:
